version: '3.8'

services:
  php:
    build:
      context: ../quiz-app
      dockerfile: ../docker/Dockerfile
    volumes:
      - ../quiz-app:/var/www/html:cached
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://app:Password123!@database:3306/app?serverVersion=8.0"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../quiz-app:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: Password123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 