version: '3.8'

services:
  php:
    build:
      context: ../quiz-app
      dockerfile: ../docker/Dockerfile.prod
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: "mysql://app:${DB_PASSWORD}@database:3306/app?serverVersion=8.0"
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../quiz-app/public:/var/www/html/public
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 