# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: quiz-app
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: quiz_app_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pdo_mysql
        coverage: xdebug

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Configure test environment
      run: |
        # Uncomment the MySQL DATABASE_URL in .env.test
        sed -i 's/# DATABASE_URL="mysql:\/\/root:root@127.0.0.1:3306\/quiz_app_test?serverVersion=8.0"/DATABASE_URL="mysql:\/\/root:root@127.0.0.1:3306\/quiz_app_test?serverVersion=8.0"/' .env.test
        # Comment out the SQLite DATABASE_URL
        sed -i 's/DATABASE_URL="sqlite:\/\/\/%kernel.project_dir%\/var\/test.db"/# DATABASE_URL="sqlite:\/\/\/%kernel.project_dir%\/var\/test.db"/' .env.test

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: quiz-app/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('quiz-app/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Dependencies
      run: |
        composer install --no-interaction --prefer-dist --verbose
        composer show

    - name: Wait for MySQL
      run: |
        until mysql -h 127.0.0.1 -u root -proot -e "SELECT 1"; do
          echo "Waiting for MySQL to be ready..."
          sleep 1
        done

    - name: Create Database
      run: |
        # For MySQL, use the doctrine:database:create command
        php bin/console doctrine:database:create --env=test --if-not-exists || true
        # For SQLite, use our custom script
        php scripts/create-test-database.php || true

    - name: Create Database Schema
      run: |
        php bin/console doctrine:schema:create --env=test

    - name: Execute tests
      env:
        APP_ENV: test
      run: vendor/bin/phpunit